name: assignment
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.0.3
  path_provider: ^2.0.11
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  badges: ^2.0.3
  cloud_firestore: ^3.3.0
  firebase_core: ^1.19.2
  firebase_auth: ^3.4.2
  json_annotation: ^4.6.0
  google_mobile_ads: ^1.3.0
#  sms: ^0.2.4
#  flutter_otp: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.3.1
  build_runner:

flutter:

  uses-material-design: true

  assets:
    - assets/data.json


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

